# Generated by Django 4.0.6 on 2022-08-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fileName',
        ),
    ]
