# Generated by Django 4.0.6 on 2022-08-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_task_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fileContent',
            field=models.CharField(max_length=10),
        ),
    ]
