# Generated by Django 4.0.6 on 2022-08-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_task_filecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='startTime',
        ),
    ]
